In [22]:
import numpy as np

In [24]:
a = [200.,         280.  ,       280.       ,  240.  ,       200.,
  200.      ,   247.05882353 ,247.05882353, 223.52941176, 200.        ],[200,       200.  ,       260.  ,       300. ,        260.,
  200,      200., 235.29411765,258.82352941,235.29411765]

In [26]:
np.array(a).T

array([[200.        , 200.        ],
       [280.        , 200.        ],
       [280.        , 260.        ],
       [240.        , 300.        ],
       [200.        , 260.        ],
       [200.        , 200.        ],
       [247.05882353, 200.        ],
       [247.05882353, 235.29411765],
       [223.52941176, 258.82352941],
       [200.        , 235.29411765]])

In [1]:
a = [1,2,3,4,5,6,7]

In [2]:
a[:3]

[1, 2, 3]

In [174]:
reconstructed_points = []
for i in range(len(three_chosen_points)):
    A_col_0 = img_coords_A[:,i][0]*CA.m_2_T-CA.m_0_T
    A_col_1 = img_coords_A[:,i][1]*CA.m_2_T-CA.m_1_T
    A_col_2 = img_coords_B[:,i][0]*CB.m_2_T-CB.m_0_T
    A_col_3 = img_coords_B[:,i][1]*CB.m_2_T-CB.m_1_T
    A = np.stack((A_col_0,A_col_1,A_col_2,A_col_3),axis=0)
    b = A[:, -1].copy()
    x = x = np.linalg.lstsq(A[:, :-1], -b)[0]
    x = np.r_[x,1]
    reconstructed_points.append(x)

reprojected_pts_4by1 = np.array(reconstructed_points).T

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if __name__ == '__main__':


In [176]:
print(three_chosen_pts_4by1)
print(reprojected_pts_4by1)

TypeError: only size-1 arrays can be converted to Python scalars

In [191]:

img_reproj_A = np.divide(CA.cam_mat.dot(reprojected_pts_4by1), CA.cam_mat.dot(reprojected_pts_4by1)[2])[:-1]
img_reproj_B = np.divide(CB.cam_mat.dot(reprojected_pts_4by1), CB.cam_mat.dot(reprojected_pts_4by1)[2])[:-1]

error_A = img_reproj_A - img_coords_A
error_B = img_reproj_B - img_coords_B

sq_sum_A = sum([error_A[:,i][0]**2+error_A[:,i][1]**2 for i in range(3)])
sq_sum_B = sum([error_B[:,i][0]**2+error_B[:,i][1]**2 for i in range(3)])

In [192]:
sq_sum_A

3.069615554396001e-26

In [193]:
sq_sum_B

7.270142102516845e-27

In [190]:
for n in error_A[:,]:
    print(n)

[-2.84217094e-14  2.84217094e-14 -1.13686838e-13]
[-5.68434189e-14 -1.13686838e-13  0.00000000e+00]


array([8.07793567e-28, 3.23117427e-27])